### ISSUE TITLE
Local Tuya

### ISSUE THREAD

**Issue by hudec111** [DzurisHome/LocalTuyaSK#3]
Ahoj,
ja som tiez zaintegroval pred nejakymi 7 mesiacmi  smart veci ale teraz uz prestali ist. To bude treba kazdeho pol roka sa nanovo registrovat v Tuya aby to fungovalo? To je potom poriadna blbost.

**Comment by milandzuris** [comment]
sprav podľa nove tutorialu ako to ma byt a možno už to pojde teraz lebo veľa veci sa zmenili

**Comment by milandzuris** [comment]
@hudec111 niečo nove?
